package exchange;

public enum ComType {
    ERROR_WITHOUT_REASON,
    ERROR_INVALID_REQUEST,
    ERROR_SQL_EXCEPT,
    
    CONNECT_RQ,
    CONNECT_RP,
    ERROR_BAD_LOGIN,
    ERROR_ALREADY_CONNECTED,

    DISCONNECT_CLI,
    DISCONNECT_SRV,
    DISCONNECT_RP,
    
    GROUPS_RQ,
    GROUPS_RP,
    
    TICKET_LIST_RQ,
    TICKET_LIST_RP,
    
    TICKET_RQ,
    TICKET_RP,
    
    NEW_TICKET_CLI,
    NEW_TICKET_SRV,
    NEW_TICKET_RP,

    NEW_MESSAGE_CLI,
    NEW_MESSAGE_SRV,
    NEW_MESSAGE_RP,

    STATUSES_RQ,
    STATUSES_RP,

    UPDATE_STATUS_CLI,
    UPDATE_STATUS_SRV,
    UPDATE_STATUS_RP
}